# -*- coding: utf-8 -*-
"""
Created on Sun Dec 27 11:59:18 2020

@author: 37212
"""
fund_manager_factor_dict = {
                    'fund_manager_1y_return': '基金近一年的绝对收益',
                    'fund_manager_3y_return': '基金近三年的绝对收益',
                    'fund_manager_5y_return': '基金近五年的绝对收益',
                    'fund_manager_1y_div_payout': '基金近一年的分红情况',
                    'fund_manager_3y_div_payout': '基金近三年的分红情况',
                    'fund_manager_5y_div_payout':'基金近五年的分红情况',
                    'fund_manager_alpha':'alpha',
                    'fund_manager_sharpe':'夏普比率',
                    'fund_manager_treynor':'特雷诺',
                    'fund_manager_ir':'信息比',
                    'fund_manager_sortino':'sortino',
                    'fund_manager_beta':'beta',
                    'fund_manager_r2':'R squared',
                    'fund_manager_excessreturn':'超额收益',
                    'fund_manager_prt_fundnetasset_total':'规模',
                    'fund_manager_prt_fundnetasset_total_growthrate':'年增长率',
                    'fund_manager_stddev':'年波动率',
                    'fund_manager_maxdrawdown_3m':'季度最大回撤',
                    'fund_manager_maxdrawdown_1y':'年度最大回撤',
                    'fund_manager_drawdown_1y':'回撤幅度',
                    'fund_manager_maxdrawdown_duration_1y':'回撤时长',
                    'fund_manager_managementfeeratio':'管理费',
                    'fund_manager_purchasefeeratio':'最高申购费',
                    'fund_manager_custodianfeeratio':'托管费',
                    'fund_manager_fund_corp_teamstability':'基金经理流动性',
                    'fund_manager_fund_liquidation':'基金公司合规性',
                    'fund_manager_fund_corp_fivestarfundsprop':'外部评级',
                    'fund_manager_holder_pct':'股权结构',
                    'fund_manager_prt_fundcototalnetassets':'资产管理规模',
                    'fund_manager_education':'学历',
                    'fund_manager_fund_averageworkingyears':'从业经验',
                    'fund_manager_fund_manager_awardrecord':'研究深度',
                    'fund_manager_holder_mngemp_holdingpct':'激励机制',
                    'fund_manager_risk_annutrackerror':'跟踪误差',
                    'fund_manager_style_stylecoefficient':'投资风格',
                    'fund_manager_prt_hkstocktonav':'投资地域敞口',
                    'fund_manager_prt_stocktonav':'仓位管理',
                    'fund_manager_prt_fundnoofsecurities':'底层资产研究',
                    'fund_manager_rating_shanghaioverall3y':'透明度',
                    'fund_manager_style_averagepositiontime':'流动性',
                    'fund_manager_prt_corporatebondtobond':'交易对手风险',
                    'fund_manager_prt_topsectosec':'市场波动风险',
                    'fund_manager_1y_periodreturnranking':'相较同业表现',
                    'fund_manager_1y_periodreturnranking_type':'相较基金经理其他产品类型表现',
                    'fund_manager_employee_board':'董事会人数',
                    'fund_manager_fund_corp_fundmanagermaturity':'员工素质',
                    'fund_manager_corp_productnopermanager':'基金公司人均管理产品数',
                    'fund_manager_regcapital':'注册资本',
                    'fund_manager_qanal_totalincome':'财务状况',
                    'fund_manager_prt_totalasset':'基金总资产值',
                    'fund_manager_div_accumulatedperunit':'基金历年分红情况',
                    'fund_manager_total_expense':'基金各种费用及成本'
                    }